const dermatologists = [
  {
    id: "d1",
    name: "Dr Yusuf Daudu. PD",
    image: "/image/doctor_1.jpg",
    rate: "N5,000/10mins",
    experience: "13+ Years of Experience",
    ratings: "⭐⭐⭐⭐⭐",
  },
  {
    id: "d2",
    name: "Dr Yusuf Daudu. PD",
    image: "/image/doctor_2.jpg",
    rate: "N5,000/10mins",
    experience: "13+ Years of Experience",
    ratings: "⭐⭐⭐⭐⭐",
  },
  {
    id: "d2",
    name: "Dr Yusuf Daudu. PD",
    image: "/image/doctor_1.jpg",
    rate: "N5,000/10mins",
    experience: "13+ Years of Experience",
    ratings: "⭐⭐⭐⭐⭐",
  },
  {
    id: "d2",
    name: "Dr Yusuf Daudu. PD",
    image: "/image/doctor_2.jpg",
    rate: "N5,000/10mins",
    experience: "13+ Years of Experience",
    ratings: "⭐⭐⭐⭐⭐",
  },
  {
    id: "d2",
    name: "Dr Yusuf Daudu. PD",
    image: "/image/doctor_1.jpg",
    rate: "N5,000/10mins",
    experience: "13+ Years of Experience",
    ratings: "⭐⭐⭐⭐⭐",
  },
  {
    id: "d2",
    name: "Dr Yusuf Daudu. PD",
    image: "/image/doctor_2.jpg",
    rate: "N5,000/10mins",
    experience: "13+ Years of Experience",
    ratings: "⭐⭐⭐⭐⭐",
  },
  {
    id: "d2",
    name: "Dr Yusuf Daudu. PD",
    image: "/image/doctor_1.jpg",
    rate: "N5,000/10mins",
    experience: "13+ Years of Experience",
    ratings: "⭐⭐⭐⭐⭐",
  },
  {
    id: "d2",
    name: "Dr Yusuf Daudu. PD",
    image: "/image/doctor_2.jpg",
    rate: "N5,000/10mins",
    experience: "13+ Years of Experience",
    ratings: "⭐⭐⭐⭐⭐",
  },
];
